#[derive(PartialEq, Copy, Clone)]
pub enum Species {
    Abra,
    Absol,
    Aerodactyl,
    Aipom,
    Anorith,
    Aron,
    Azurill,
    Bagon,
    Baltoy,
    Barboach,
    Beldum,
    Bellsprout,
    Bulbasaur,
    Cacnea,
    Carvanha,
    Castform,
    Caterpie,
    Chansey,
    Charmander,
    Chikorita,
    Chimecho,
    Chinchou,
    Clamperl,
    Cleffa,
    Corphish,
    Corsola,
    Cubone,
    Cyndaquil,
    Delibird,
    Deoxys,
    Diglett,
    Doduo,
    Dratini,
    Drowzee,
    Dunsparce,
    Duskull,
    Eevee,
    Ekans,
    Electrike,
    Electrode,
    Elekid,
    Exeggcute,
    Farfetchd,
    Feebas,
    Gastly,
    Geodude,
    Girafarig,
    Gligar,
    Goldeen,
    Grimer,
    Groudon,
    Growlithe,
    Gulpin,
    Heracross,
    HoOh,
    Hoothoot,
    Hoppip,
    Horsea,
    Houndour,
    Igglybuff,
    Illumise,
    Kabuto,
    Kangaskhan,
    Kecleon,
    Koffing,
    Krabby,
    Kyogre,
    Lapras,
    Larvitar,
    Latias,
    Latios,
    Ledyba,
    Lickitung,
    Lileep,
    Lotad,
    Lugia,
    Lunatone,
    Luvdisc,
    Machop,
    Magby,
    Magikarp,
    Magnemite,
    Makuhita,
    Mankey,
    Mantine,
    Mareep,
    Marill,
    Mawile,
    Meditite,
    Meowth,
    Mew,
    Miltank,
    Minun,
    Misdreavus,
    MrMime,
    Mudkip,
    Murkrow,
    Natu,
    NidoranFemale,
    NidoranMale,
    Nincada,
    Nosepass,
    Numel,
    Oddish,
    Omanyte,
    Onix,
    Paras,
    Phanpy,
    Pichu,
    Pidgey,
    Pineco,
    Pinsir,
    Plusle,
    Poliwag,
    Ponyta,
    Poochyena,
    Porygon,
    Psyduck,
    Qwilfish,
    Ralts,
    Rattata,
    Rayquaza,
    Regice,
    Regirock,
    Registeel,
    Relicanth,
    Remoraid,
    Rhyhorn,
    Roselia,
    Sableye,
    Sandshrew,
    Scyther,
    Seedot,
    Seel,
    Sentret,
    Seviper,
    Shellder,
    Shroomish,
    Shuckle,
    Shuppet,
    Skarmory,
    Skitty,
    Slakoth,
    Slowpoke,
    Slugma,
    Smeargle,
    Smoochum,
    Sneasel,
    Snorlax,
    Snorunt,
    Snubbull,
    Solrock,
    Spearow,
    Spheal,
    Spinarak,
    Spinda,
    Spoink,
    Squirtle,
    Stantler,
    Staryu,
    Sudowoodo,
    Sunkern,
    Surskit,
    Swablu,
    Swinub,
    Taillow,
    Tangela,
    Tauros,
    Teddiursa,
    Tentacool,
    Togepi,
    Torchic,
    Torkoal,
    Totodile,
    Trapinch,
    Treecko,
    Tropius,
    Tyrogue,
    Venonat,
    Volbeat,
    Voltorb,
    Vulpix,
    Wailmer,
    Weedle,
    Whismur,
    Wingull,
    Wobbuffet,
    Wooper,
    Wurmple,
    Wynaut,
    Yanma,
    Zangoose,
    Zigzagoon,
    Zubat,
}

impl Species {
    pub fn to_str(&self) -> &'static str {
        use Species::*;
        match self {
            Abra => "Abra",
            Absol => "Absol",
            Aerodactyl => "Aerodactyl",
            Aipom => "Aipom",
            Anorith => "Anorith",
            Aron => "Aron",
            Azurill => "Azurill",
            Bagon => "Bagon",
            Baltoy => "Baltoy",
            Barboach => "Barboach",
            Beldum => "Beldum",
            Bellsprout => "Bellsprout",
            Bulbasaur => "Bulbasaur",
            Cacnea => "Cacnea",
            Carvanha => "Carvanha",
            Castform => "Castform",
            Caterpie => "Caterpie",
            Chansey => "Chansey",
            Charmander => "Charmander",
            Chikorita => "Chikorita",
            Chimecho => "Chimecho",
            Chinchou => "Chinchou",
            Clamperl => "Clamperl",
            Cleffa => "Cleffa",
            Corphish => "Corphish",
            Corsola => "Corsola",
            Cubone => "Cubone",
            Cyndaquil => "Cyndaquil",
            Delibird => "Delibird",
            Deoxys => "Deoxys",
            Diglett => "Diglett",
            Doduo => "Doduo",
            Dratini => "Dratini",
            Drowzee => "Drowzee",
            Dunsparce => "Dunsparce",
            Duskull => "Duskull",
            Eevee => "Eevee",
            Ekans => "Ekans",
            Electrike => "Electrike",
            Electrode => "Electrode",
            Elekid => "Elekid",
            Exeggcute => "Exeggcute",
            Farfetchd => "Farfetch'd",
            Feebas => "Feebas",
            Gastly => "Gastly",
            Geodude => "Geodude",
            Girafarig => "Girafarig",
            Gligar => "Gligar",
            Goldeen => "Goldeen",
            Grimer => "Grimer",
            Groudon => "Groudon",
            Growlithe => "Growlithe",
            Gulpin => "Gulpin",
            Heracross => "Heracross",
            HoOh => "Ho-Oh",
            Hoothoot => "Hoothoot",
            Hoppip => "Hoppip",
            Horsea => "Horsea",
            Houndour => "Houndour",
            Igglybuff => "Igglybuff",
            Illumise => "Illumise",
            Kabuto => "Kabuto",
            Kangaskhan => "Kangaskhan",
            Kecleon => "Kecleon",
            Koffing => "Koffing",
            Krabby => "Krabby",
            Kyogre => "Kyogre",
            Lapras => "Lapras",
            Larvitar => "Larvitar",
            Latias => "Latias",
            Latios => "Latios",
            Ledyba => "Ledyba",
            Lickitung => "Lickitung",
            Lileep => "Lileep",
            Lotad => "Lotad",
            Lugia => "Lugia",
            Lunatone => "Lunatone",
            Luvdisc => "Luvdisc",
            Machop => "Machop",
            Magby => "Magby",
            Magikarp => "Magikarp",
            Magnemite => "Magnemite",
            Makuhita => "Makuhita",
            Mankey => "Mankey",
            Mantine => "Mantine",
            Mareep => "Mareep",
            Marill => "Marill",
            Mawile => "Mawile",
            Meditite => "Meditite",
            Meowth => "Meowth",
            Mew => "Mew",
            Miltank => "Miltank",
            Minun => "Minun",
            Misdreavus => "Misdreavus",
            MrMime => "Mr. Mime",
            Mudkip => "Mudkip",
            Murkrow => "Murkrow",
            Natu => "Natu",
            NidoranFemale => "Nidoran♀",
            NidoranMale => "Nidoran♂",
            Nincada => "Nincada",
            Nosepass => "Nosepass",
            Numel => "Numel",
            Oddish => "Oddish",
            Omanyte => "Omanyte",
            Onix => "Onix",
            Paras => "Paras",
            Phanpy => "Phanpy",
            Pichu => "Pichu",
            Pidgey => "Pidgey",
            Pineco => "Pineco",
            Pinsir => "Pinsir",
            Plusle => "Plusle",
            Poliwag => "Poliwag",
            Ponyta => "Ponyta",
            Poochyena => "Poochyena",
            Porygon => "Porygon",
            Psyduck => "Psyduck",
            Qwilfish => "Qwilfish",
            Ralts => "Ralts",
            Rattata => "Rattata",
            Rayquaza => "Rayquaza",
            Regice => "Regice",
            Regirock => "Regirock",
            Registeel => "Registeel",
            Relicanth => "Relicanth",
            Remoraid => "Remoraid",
            Rhyhorn => "Rhyhorn",
            Roselia => "Roselia",
            Sableye => "Sableye",
            Sandshrew => "Sandshrew",
            Scyther => "Scyther",
            Seedot => "Seedot",
            Seel => "Seel",
            Sentret => "Sentret",
            Seviper => "Seviper",
            Shellder => "Shellder",
            Shroomish => "Shroomish",
            Shuckle => "Shuckle",
            Shuppet => "Shuppet",
            Skarmory => "Skarmory",
            Skitty => "Skitty",
            Slakoth => "Slakoth",
            Slowpoke => "Slowpoke",
            Slugma => "Slugma",
            Smeargle => "Smeargle",
            Smoochum => "Smoochum",
            Sneasel => "Sneasel",
            Snorlax => "Snorlax",
            Snorunt => "Snorunt",
            Snubbull => "Snubbull",
            Solrock => "Solrock",
            Spearow => "Spearow",
            Spheal => "Spheal",
            Spinarak => "Spinarak",
            Spinda => "Spinda",
            Spoink => "Spoink",
            Squirtle => "Squirtle",
            Stantler => "Stantler",
            Staryu => "Staryu",
            Sudowoodo => "Sudowoodo",
            Sunkern => "Sunkern",
            Surskit => "Surskit",
            Swablu => "Swablu",
            Swinub => "Swinub",
            Taillow => "Taillow",
            Tangela => "Tangela",
            Tauros => "Tauros",
            Teddiursa => "Teddiursa",
            Tentacool => "Tentacool",
            Togepi => "Togepi",
            Torchic => "Torchic",
            Torkoal => "Torkoal",
            Totodile => "Totodile",
            Trapinch => "Trapinch",
            Treecko => "Treecko",
            Tropius => "Tropius",
            Tyrogue => "Tyrogue",
            Venonat => "Venonat",
            Volbeat => "Volbeat",
            Voltorb => "Voltorb",
            Vulpix => "Vulpix",
            Wailmer => "Wailmer",
            Weedle => "Weedle",
            Whismur => "Whismur",
            Wingull => "Wingull",
            Wobbuffet => "Wobbuffet",
            Wooper => "Wooper",
            Wurmple => "Wurmple",
            Wynaut => "Wynaut",
            Yanma => "Yanma",
            Zangoose => "Zangoose",
            Zigzagoon => "Zigzagoon",
            Zubat => "Zubat",
        }
    }

    pub fn get_abilities(&self) -> (Ability, Option<Ability>) {
        use Ability::*;
        use Species::*;
        match self {
            Abra => (Synchronize, Some(InnerFocus)),
            Absol => (Pressure, None),
            Aerodactyl => (RockHead, Some(Pressure)),
            Aipom => (RunAway, Some(Pickup)),
            Anorith => (BattleArmor, None),
            Aron => (Sturdy, Some(RockHead)),
            Azurill => (ThickFat, Some(HugePower)),
            Bagon => (RockHead, None),
            Baltoy => (Levitate, None),
            Barboach => (Oblivious, None),
            Beldum => (ClearBody, None),
            Bellsprout => (Chlorophyll, None),
            Bulbasaur => (Overgrow, None),
            Cacnea => (SandVeil, None),
            Carvanha => (RoughSkin, None),
            Castform => (Forecast, None),
            Caterpie => (ShieldDust, None),
            Chansey => (NaturalCure, Some(SereneGrace)),
            Charmander => (Blaze, None),
            Chikorita => (Overgrow, None),
            Chimecho => (Levitate, None),
            Chinchou => (VoltAbsorb, Some(Illuminate)),
            Clamperl => (ShellArmor, None),
            Cleffa => (CuteCharm, None),
            Corphish => (HyperCutter, Some(ShellArmor)),
            Corsola => (Hustle, Some(NaturalCure)),
            Cubone => (RockHead, Some(LightningRod)),
            Cyndaquil => (Blaze, None),
            Delibird => (VitalSpirit, Some(Hustle)),
            Deoxys => (Pressure, None),
            Diglett => (SandVeil, Some(ArenaTrap)),
            Doduo => (RunAway, Some(EarlyBird)),
            Dratini => (ShedSkin, None),
            Drowzee => (Insomnia, None),
            Dunsparce => (SereneGrace, Some(RunAway)),
            Duskull => (Levitate, None),
            Eevee => (RunAway, None),
            Ekans => (Intimidate, Some(ShedSkin)),
            Electrike => (Static, Some(LightningRod)),
            Electrode => (Soundproof, Some(Static)),
            Elekid => (Static, None),
            Exeggcute => (Chlorophyll, None),
            Farfetchd => (KeenEye, Some(InnerFocus)),
            Feebas => (SwiftSwim, None),
            Gastly => (Levitate, None),
            Geodude => (RockHead, Some(Sturdy)),
            Girafarig => (InnerFocus, Some(EarlyBird)),
            Gligar => (HyperCutter, Some(SandVeil)),
            Goldeen => (SwiftSwim, Some(WaterVeil)),
            Grimer => (Stench, Some(StickyHold)),
            Groudon => (Drought, None),
            Growlithe => (Intimidate, Some(FlashFire)),
            Gulpin => (LiquidOoze, Some(StickyHold)),
            Heracross => (Swarm, Some(Guts)),
            HoOh => (Pressure, None),
            Hoothoot => (Insomnia, Some(KeenEye)),
            Hoppip => (Chlorophyll, None),
            Horsea => (SwiftSwim, None),
            Houndour => (EarlyBird, Some(FlashFire)),
            Igglybuff => (CuteCharm, None),
            Illumise => (Oblivious, None),
            Kabuto => (SwiftSwim, Some(BattleArmor)),
            Kangaskhan => (EarlyBird, None),
            Kecleon => (ColorChange, None),
            Koffing => (Levitate, None),
            Krabby => (HyperCutter, Some(ShellArmor)),
            Kyogre => (Drizzle, None),
            Lapras => (WaterAbsorb, Some(ShellArmor)),
            Larvitar => (Guts, None),
            Latias => (Levitate, None),
            Latios => (Levitate, None),
            Ledyba => (Swarm, Some(EarlyBird)),
            Lickitung => (OwnTempo, Some(Oblivious)),
            Lileep => (SuctionCups, None),
            Lotad => (SwiftSwim, Some(RainDish)),
            Lugia => (Pressure, None),
            Lunatone => (Levitate, None),
            Luvdisc => (SwiftSwim, None),
            Machop => (Guts, None),
            Magby => (FlameBody, None),
            Magikarp => (SwiftSwim, None),
            Magnemite => (MagnetPull, Some(Sturdy)),
            Makuhita => (ThickFat, Some(Guts)),
            Mankey => (VitalSpirit, None),
            Mantine => (SwiftSwim, Some(WaterAbsorb)),
            Mareep => (Static, None),
            Marill => (ThickFat, Some(HugePower)),
            Mawile => (HyperCutter, Some(Intimidate)),
            Meditite => (PurePower, None),
            Meowth => (Pickup, None),
            Mew => (Synchronize, None),
            Miltank => (ThickFat, None),
            Minun => (Minus, None),
            Misdreavus => (Levitate, None),
            MrMime => (Soundproof, None),
            Mudkip => (Torrent, None),
            Murkrow => (Insomnia, None),
            Natu => (Synchronize, Some(EarlyBird)),
            NidoranFemale => (PoisonPoint, None),
            NidoranMale => (PoisonPoint, None),
            Nincada => (CompoundEyes, None),
            Nosepass => (Sturdy, Some(MagnetPull)),
            Numel => (Oblivious, None),
            Oddish => (Chlorophyll, None),
            Omanyte => (SwiftSwim, Some(ShellArmor)),
            Onix => (RockHead, Some(Sturdy)),
            Paras => (EffectSpore, None),
            Phanpy => (Pickup, None),
            Pichu => (Static, None),
            Pidgey => (KeenEye, None),
            Pineco => (Sturdy, None),
            Pinsir => (HyperCutter, None),
            Plusle => (Plus, None),
            Poliwag => (WaterAbsorb, Some(Damp)),
            Ponyta => (RunAway, Some(FlashFire)),
            Poochyena => (RunAway, None),
            Porygon => (Trace, None),
            Psyduck => (Damp, Some(CloudNine)),
            Qwilfish => (PoisonPoint, Some(SwiftSwim)),
            Ralts => (Synchronize, Some(Trace)),
            Rattata => (RunAway, Some(Guts)),
            Rayquaza => (AirLock, None),
            Regice => (ClearBody, None),
            Regirock => (ClearBody, None),
            Registeel => (ClearBody, None),
            Relicanth => (SwiftSwim, Some(RockHead)),
            Remoraid => (Hustle, None),
            Rhyhorn => (LightningRod, Some(RockHead)),
            Roselia => (NaturalCure, Some(PoisonPoint)),
            Sableye => (KeenEye, None),
            Sandshrew => (SandVeil, None),
            Scyther => (Swarm, None),
            Seedot => (Chlorophyll, Some(EarlyBird)),
            Seel => (ThickFat, None),
            Sentret => (RunAway, Some(KeenEye)),
            Seviper => (ShedSkin, None),
            Shellder => (ShellArmor, None),
            Shroomish => (EffectSpore, None),
            Shuckle => (Sturdy, None),
            Shuppet => (Insomnia, None),
            Skarmory => (KeenEye, Some(Sturdy)),
            Skitty => (CuteCharm, None),
            Slakoth => (Truant, None),
            Slowpoke => (Oblivious, Some(OwnTempo)),
            Slugma => (MagmaArmor, Some(FlameBody)),
            Smeargle => (OwnTempo, None),
            Smoochum => (Oblivious, None),
            Sneasel => (InnerFocus, Some(KeenEye)),
            Snorlax => (Immunity, Some(ThickFat)),
            Snorunt => (InnerFocus, None),
            Snubbull => (Intimidate, Some(RunAway)),
            Solrock => (Levitate, None),
            Spearow => (KeenEye, None),
            Spheal => (ThickFat, None),
            Spinarak => (Swarm, Some(Insomnia)),
            Spinda => (OwnTempo, None),
            Spoink => (ThickFat, Some(OwnTempo)),
            Squirtle => (Torrent, None),
            Stantler => (Intimidate, None),
            Staryu => (Illuminate, Some(NaturalCure)),
            Sudowoodo => (RockHead, Some(Sturdy)),
            Sunkern => (Chlorophyll, None),
            Surskit => (SwiftSwim, None),
            Swablu => (NaturalCure, None),
            Swinub => (Oblivious, None),
            Taillow => (Guts, None),
            Tangela => (Chlorophyll, None),
            Tauros => (Intimidate, None),
            Teddiursa => (Pickup, None),
            Tentacool => (ClearBody, Some(LiquidOoze)),
            Togepi => (Hustle, Some(SereneGrace)),
            Torchic => (Blaze, None),
            Torkoal => (WhiteSmoke, None),
            Totodile => (Torrent, None),
            Trapinch => (HyperCutter, Some(ArenaTrap)),
            Treecko => (Overgrow, None),
            Tropius => (Chlorophyll, None),
            Tyrogue => (Guts, None),
            Venonat => (CompoundEyes, None),
            Volbeat => (Illuminate, Some(Swarm)),
            Voltorb => (Soundproof, Some(Static)),
            Vulpix => (FlashFire, None),
            Wailmer => (WaterVeil, Some(Oblivious)),
            Weedle => (ShieldDust, None),
            Whismur => (Soundproof, None),
            Wingull => (KeenEye, None),
            Wobbuffet => (ShadowTag, None),
            Wooper => (Damp, Some(WaterAbsorb)),
            Wurmple => (ShieldDust, None),
            Wynaut => (ShadowTag, None),
            Yanma => (SpeedBoost, Some(CompoundEyes)),
            Zangoose => (Immunity, None),
            Zigzagoon => (Pickup, None),
            Zubat => (InnerFocus, None),
        }
    }

    pub fn get_gender_ratio(&self) -> GenderRatio {
        use GenderRatio::*;
        use Species::*;
        match self {
            Abra => Seventyfive_Twentyfive,
            Absol => Fifty_Fifty,
            Aerodactyl => Eightysevenpointfive_Twelvepointfive,
            Aipom => Fifty_Fifty,
            Anorith => Eightysevenpointfive_Twelvepointfive,
            Aron => Fifty_Fifty,
            Azurill => Twentyfive_Seventyfive,
            Bagon => Fifty_Fifty,
            Baltoy => Genderless,
            Barboach => Fifty_Fifty,
            Beldum => Genderless,
            Bellsprout => Fifty_Fifty,
            Bulbasaur => Eightysevenpointfive_Twelvepointfive,
            Cacnea => Fifty_Fifty,
            Carvanha => Fifty_Fifty,
            Castform => Fifty_Fifty,
            Caterpie => Fifty_Fifty,
            Chansey => AlwaysFemale,
            Charmander => Eightysevenpointfive_Twelvepointfive,
            Chikorita => Eightysevenpointfive_Twelvepointfive,
            Chimecho => Fifty_Fifty,
            Chinchou => Fifty_Fifty,
            Clamperl => Fifty_Fifty,
            Cleffa => Twentyfive_Seventyfive,
            Corphish => Fifty_Fifty,
            Corsola => Twentyfive_Seventyfive,
            Cubone => Fifty_Fifty,
            Cyndaquil => Eightysevenpointfive_Twelvepointfive,
            Delibird => Fifty_Fifty,
            Deoxys => Genderless,
            Diglett => Fifty_Fifty,
            Doduo => Fifty_Fifty,
            Dratini => Fifty_Fifty,
            Drowzee => Fifty_Fifty,
            Dunsparce => Fifty_Fifty,
            Duskull => Fifty_Fifty,
            Eevee => Eightysevenpointfive_Twelvepointfive,
            Ekans => Fifty_Fifty,
            Electrike => Fifty_Fifty,
            Electrode => Genderless,
            Elekid => Seventyfive_Twentyfive,
            Exeggcute => Fifty_Fifty,
            Farfetchd => Fifty_Fifty,
            Feebas => Fifty_Fifty,
            Gastly => Fifty_Fifty,
            Geodude => Fifty_Fifty,
            Girafarig => Fifty_Fifty,
            Gligar => Fifty_Fifty,
            Goldeen => Fifty_Fifty,
            Grimer => Fifty_Fifty,
            Groudon => Genderless,
            Growlithe => Seventyfive_Twentyfive,
            Gulpin => Fifty_Fifty,
            Heracross => Fifty_Fifty,
            HoOh => Genderless,
            Hoothoot => Fifty_Fifty,
            Hoppip => Fifty_Fifty,
            Horsea => Fifty_Fifty,
            Houndour => Fifty_Fifty,
            Igglybuff => Twentyfive_Seventyfive,
            Illumise => AlwaysFemale,
            Kabuto => Eightysevenpointfive_Twelvepointfive,
            Kangaskhan => AlwaysFemale,
            Kecleon => Fifty_Fifty,
            Koffing => Fifty_Fifty,
            Krabby => Fifty_Fifty,
            Kyogre => Genderless,
            Lapras => Fifty_Fifty,
            Larvitar => Fifty_Fifty,
            Latias => AlwaysFemale,
            Latios => AlwaysMale,
            Ledyba => Fifty_Fifty,
            Lickitung => Fifty_Fifty,
            Lileep => Eightysevenpointfive_Twelvepointfive,
            Lotad => Fifty_Fifty,
            Lugia => Genderless,
            Lunatone => Genderless,
            Luvdisc => Twentyfive_Seventyfive,
            Machop => Seventyfive_Twentyfive,
            Magby => Seventyfive_Twentyfive,
            Magikarp => Fifty_Fifty,
            Magnemite => Genderless,
            Makuhita => Seventyfive_Twentyfive,
            Mankey => Fifty_Fifty,
            Mantine => Fifty_Fifty,
            Mareep => Fifty_Fifty,
            Marill => Fifty_Fifty,
            Mawile => Fifty_Fifty,
            Meditite => Fifty_Fifty,
            Meowth => Fifty_Fifty,
            Mew => Genderless,
            Miltank => AlwaysFemale,
            Minun => Fifty_Fifty,
            Misdreavus => Fifty_Fifty,
            MrMime => Fifty_Fifty,
            Mudkip => Eightysevenpointfive_Twelvepointfive,
            Murkrow => Fifty_Fifty,
            Natu => Fifty_Fifty,
            NidoranFemale => AlwaysFemale,
            NidoranMale => AlwaysMale,
            Nincada => Fifty_Fifty,
            Nosepass => Fifty_Fifty,
            Numel => Fifty_Fifty,
            Oddish => Fifty_Fifty,
            Omanyte => Eightysevenpointfive_Twelvepointfive,
            Onix => Fifty_Fifty,
            Paras => Fifty_Fifty,
            Phanpy => Fifty_Fifty,
            Pichu => Fifty_Fifty,
            Pidgey => Fifty_Fifty,
            Pineco => Fifty_Fifty,
            Pinsir => Fifty_Fifty,
            Plusle => Fifty_Fifty,
            Poliwag => Fifty_Fifty,
            Ponyta => Fifty_Fifty,
            Poochyena => Fifty_Fifty,
            Porygon => Genderless,
            Psyduck => Fifty_Fifty,
            Qwilfish => Fifty_Fifty,
            Ralts => Fifty_Fifty,
            Rattata => Fifty_Fifty,
            Rayquaza => Genderless,
            Regice => Genderless,
            Regirock => Genderless,
            Registeel => Genderless,
            Relicanth => Eightysevenpointfive_Twelvepointfive,
            Remoraid => Fifty_Fifty,
            Rhyhorn => Fifty_Fifty,
            Roselia => Fifty_Fifty,
            Sableye => Fifty_Fifty,
            Sandshrew => Fifty_Fifty,
            Scyther => Fifty_Fifty,
            Seedot => Fifty_Fifty,
            Seel => Fifty_Fifty,
            Sentret => Fifty_Fifty,
            Seviper => Fifty_Fifty,
            Shellder => Fifty_Fifty,
            Shroomish => Fifty_Fifty,
            Shuckle => Fifty_Fifty,
            Shuppet => Fifty_Fifty,
            Skarmory => Fifty_Fifty,
            Skitty => Twentyfive_Seventyfive,
            Slakoth => Fifty_Fifty,
            Slowpoke => Fifty_Fifty,
            Slugma => Fifty_Fifty,
            Smeargle => Fifty_Fifty,
            Smoochum => AlwaysFemale,
            Sneasel => Fifty_Fifty,
            Snorlax => Eightysevenpointfive_Twelvepointfive,
            Snorunt => Fifty_Fifty,
            Snubbull => Twentyfive_Seventyfive,
            Solrock => Genderless,
            Spearow => Fifty_Fifty,
            Spheal => Fifty_Fifty,
            Spinarak => Fifty_Fifty,
            Spinda => Fifty_Fifty,
            Spoink => Fifty_Fifty,
            Squirtle => Eightysevenpointfive_Twelvepointfive,
            Stantler => Fifty_Fifty,
            Staryu => Genderless,
            Sudowoodo => Fifty_Fifty,
            Sunkern => Fifty_Fifty,
            Surskit => Fifty_Fifty,
            Swablu => Fifty_Fifty,
            Swinub => Fifty_Fifty,
            Taillow => Fifty_Fifty,
            Tangela => Fifty_Fifty,
            Tauros => AlwaysMale,
            Teddiursa => Fifty_Fifty,
            Tentacool => Fifty_Fifty,
            Togepi => Eightysevenpointfive_Twelvepointfive,
            Torchic => Eightysevenpointfive_Twelvepointfive,
            Torkoal => Fifty_Fifty,
            Totodile => Eightysevenpointfive_Twelvepointfive,
            Trapinch => Fifty_Fifty,
            Treecko => Eightysevenpointfive_Twelvepointfive,
            Tropius => Fifty_Fifty,
            Tyrogue => AlwaysMale,
            Venonat => Fifty_Fifty,
            Volbeat => AlwaysMale,
            Voltorb => Genderless,
            Vulpix => Twentyfive_Seventyfive,
            Wailmer => Fifty_Fifty,
            Weedle => Fifty_Fifty,
            Whismur => Fifty_Fifty,
            Wingull => Fifty_Fifty,
            Wobbuffet => Fifty_Fifty,
            Wooper => Fifty_Fifty,
            Wurmple => Fifty_Fifty,
            Wynaut => Fifty_Fifty,
            Yanma => Fifty_Fifty,
            Zangoose => Fifty_Fifty,
            Zigzagoon => Fifty_Fifty,
            Zubat => Fifty_Fifty,
        }
    }
}

#[derive(PartialEq, Copy, Clone)]
pub enum Nature {
    Adamant,
    Bashful,
    Bold,
    Brave,
    Calm,
    Careful,
    Docile,
    Gentle,
    Hardy,
    Hasty,
    Impish,
    Jolly,
    Lax,
    Lonely,
    Mild,
    Modest,
    Naive,
    Naughty,
    Quiet,
    Quirky,
    Rash,
    Relaxed,
    Sassy,
    Serious,
    Timid,
}

impl Nature {
    pub fn to_str(&self) -> &'static str {
        use Nature::*;
        match self {
            Adamant => "Adamant",
            Bashful => "Bashful",
            Bold => "Bold",
            Brave => "Brave",
            Calm => "Calm",
            Careful => "Careful",
            Docile => "Docile",
            Gentle => "Gentle",
            Hardy => "Hardy",
            Hasty => "Hasty",
            Impish => "Impish",
            Jolly => "Jolly",
            Lax => "Lax",
            Lonely => "Lonely",
            Mild => "Mild",
            Modest => "Modest",
            Naive => "Naive",
            Naughty => "Naughty",
            Quiet => "Quiet",
            Quirky => "Quirky",
            Rash => "Rash",
            Relaxed => "Relaxed",
            Sassy => "Sassy",
            Serious => "Serious",
            Timid => "Timid",
        }
    }
}

#[derive(PartialEq, Copy, Clone)]
pub enum Ability {
    AirLock,
    ArenaTrap,
    BattleArmor,
    Blaze,
    Chlorophyll,
    ClearBody,
    CloudNine,
    ColorChange,
    CompoundEyes,
    CuteCharm,
    Damp,
    Drizzle,
    Drought,
    EarlyBird,
    EffectSpore,
    FlameBody,
    FlashFire,
    Forecast,
    Guts,
    HugePower,
    Hustle,
    HyperCutter,
    Illuminate,
    Immunity,
    InnerFocus,
    Insomnia,
    Intimidate,
    KeenEye,
    Levitate,
    LightningRod,
    LiquidOoze,
    MagmaArmor,
    MagnetPull,
    Minus,
    NaturalCure,
    Oblivious,
    Overgrow,
    OwnTempo,
    Pickup,
    Plus,
    PoisonPoint,
    Pressure,
    PurePower,
    RainDish,
    RockHead,
    RoughSkin,
    RunAway,
    SandVeil,
    SereneGrace,
    ShadowTag,
    ShedSkin,
    ShellArmor,
    ShieldDust,
    Soundproof,
    SpeedBoost,
    Static,
    Stench,
    StickyHold,
    Sturdy,
    SuctionCups,
    Swarm,
    SwiftSwim,
    Synchronize,
    ThickFat,
    Torrent,
    Trace,
    Truant,
    VitalSpirit,
    VoltAbsorb,
    WaterAbsorb,
    WaterVeil,
    WhiteSmoke,
}

impl Ability {
    pub fn to_str(&self) -> &'static str {
        use Ability::*;
        match self {
            AirLock => "Air Lock",
            ArenaTrap => "Arena Trap",
            BattleArmor => "Battle Armor",
            Blaze => "Blaze",
            Chlorophyll => "Chlorophyll",
            ClearBody => "Clear Body",
            CloudNine => "Cloud Nine",
            ColorChange => "Color Change",
            CompoundEyes => "Compound Eyes",
            CuteCharm => "Cute Charm",
            Damp => "Damp",
            Drizzle => "Drizzle",
            Drought => "Drought",
            EarlyBird => "Early Bird",
            EffectSpore => "Effect Spore",
            FlameBody => "Flame Body",
            FlashFire => "Flash Fire",
            Forecast => "Forecast",
            Guts => "Guts",
            HugePower => "Huge Power",
            Hustle => "Hustle",
            HyperCutter => "Hyper Cutter",
            Illuminate => "Illuminate",
            Immunity => "Immunity",
            InnerFocus => "Inner Focus",
            Insomnia => "Insomnia",
            Intimidate => "Intimidate",
            KeenEye => "Keen Eye",
            Levitate => "Levitate",
            LightningRod => "Lightning Rod",
            LiquidOoze => "Liquid Ooze",
            MagmaArmor => "Magma Armor",
            MagnetPull => "Magnet Pull",
            Minus => "Minus",
            NaturalCure => "Natural Cure",
            Oblivious => "Oblivious",
            Overgrow => "Overgrow",
            OwnTempo => "Own Tempo",
            Pickup => "Pickup",
            Plus => "Plus",
            PoisonPoint => "Poison Point",
            Pressure => "Pressure",
            PurePower => "Pure Power",
            RainDish => "Rain Dish",
            RockHead => "Rock Head",
            RoughSkin => "Rough Skin",
            RunAway => "Run Away",
            SandVeil => "Sand Veil",
            SereneGrace => "Serene Grace",
            ShadowTag => "Shadow Tag",
            ShedSkin => "Shed Skin",
            ShellArmor => "Shell Armor",
            ShieldDust => "Shield Dust",
            Soundproof => "Soundproof",
            SpeedBoost => "Speed Boost",
            Static => "Static",
            Stench => "Stench",
            StickyHold => "Sticky Hold",
            Sturdy => "Sturdy",
            SuctionCups => "Suction Cups",
            Swarm => "Swarm",
            SwiftSwim => "Swift Swim",
            Synchronize => "Synchronize",
            ThickFat => "Thick Fat",
            Torrent => "Torrent",
            Trace => "Trace",
            Truant => "Truant",
            VitalSpirit => "Vital Spirit",
            VoltAbsorb => "Volt Absorb",
            WaterAbsorb => "Water Absorb",
            WaterVeil => "Water Veil",
            WhiteSmoke => "White Smoke",
        }
    }
}

#[derive(PartialEq, Copy, Clone)]
pub enum Gender {
    Genderless,
    Male,
    Female,
}

impl Gender {
    pub fn to_str(&self) -> &'static str {
        use Gender::*;
        match self {
            Genderless => "Genderless",
            Male => "Male",
            Female => "Female",
        }
    }
}

#[allow(non_camel_case_types)]
#[derive(PartialEq, Copy, Clone)]
pub enum GenderRatio {
    Genderless,
    AlwaysMale,
    AlwaysFemale,
    // Male:Female % ratio
    Twentyfive_Seventyfive,
    Fifty_Fifty,
    Seventyfive_Twentyfive,
    Eightysevenpointfive_Twelvepointfive,
}

pub enum IVComparator {
    Any,
    Equal,
    GreaterThanOrEqual,
    LessThanOrEqual,
}

impl IVComparator {
    pub fn test(&self, test_iv: u8, filter_iv: u8) -> bool {
        use IVComparator::*;
        match self {
            Any => true,
            Equal => test_iv == filter_iv,
            GreaterThanOrEqual => test_iv >= filter_iv,
            LessThanOrEqual => test_iv <= filter_iv,
        }
    }
}
